---
- name: Include var files
  include_vars:
    dir: vars

- name: Create Environment all file
  template:
    src: all.j2
    dest: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/all"
    force: yes
    owner: "{{ lookup('env', 'USER') }}"
    output_encoding: utf-8
    mode: 0644

- name: Check if vnet already exists
  azure_rm_virtualnetwork_facts:
    resource_group: "{{ master_project_name }}-rg"
    name: "vnet-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'env_type') }}"
  register: vnetcheck

- name: Calculate vnet address space prefix
  import_role:
    name: calculate-vnet-prefix
  when: vnetcheck.virtualnetworks == []

- name: Replace anchor with vnet prefix in all file
  replace:
    path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/all"
    replace: "{{ vnetcheck.virtualnetworks[0].address_prefixes[0].split('.')[:3] | join('.') }}"
    regexp: "VNET-ANCOR"
  when: vnetcheck.virtualnetworks != []

- name: Check if Azure Dynamic inventory file exists
  stat:
    path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/azure_rm.yml"
  register: azure_rm_file

- name: Create azure dynamic inventory file
  template:
    dest: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/azure_rm.yml"
    src: azure_rm.j2
    force: yes
    owner: "{{ lookup('env', 'USER') }}"
    output_encoding: utf-8
    mode: 0644
  when: azure_rm_file.stat.exists == false
