---
- name: Include var files
  include_vars:
    dir: vars

- name: Create environment all file
  import_tasks: create-environment-allfile.yml

- name: Create vnet
  import_tasks: create-vnet-prefix.yml