---
# tasks file for azure-keyvault
- name: Create secret in {{ cloud_config.azkeyvault.name }} KeyVault
  azure_rm_keyvaultsecret:
    secret_name: "{{ cloud_config.sql_server.secret_name }}"
    secret_value: "{{ secret_result }}"
    keyvault_uri: "{{ cloud_config.azkeyvault.uri }}" 
