---
# tasks file for azure-keyvault
- name: Create secret in {{ cloud_config.azkeyvault.name }} KeyVault
  azure_rm_keyvaultsecret:
    subscription_id: "{{ cloud_config.azkeyvault.subscription_id  }}" 
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}" 
    secret_name: "{{ secret_name }}"
    secret_value: "{{ secret_result }}"
    keyvault_uri: "{{ cloud_config.azkeyvault.uri }}" 
