---
# tasks file for azure-keyvault
- name: Generate random secret
  set_fact:
    secret_result: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits,punctuation') }}"        
