---
# All common linux OS related tasks are goes heir
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "main.yml"
      paths:
        - ../common/vars

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages | join(',') }}"
  became: true

- name: Install Java
  include_tasks: java.yml

- name: Make sure the NTP service is started
  service:
    name: "{{ ntp_service_name }}"
    state: started

- name: Make sure the NTP service is enabled
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
  ignore_errors: true

- name: Make sure /etc/security/limits.d exists
  file:                
    path: /etc/security/limits.d
    mode: 0755         
    state: directory   
                       
- name: Set nofile and nproc limits
  blockinfile:         
    path: /etc/security/limits.d/99-hadoop.conf
    create: yes        
    mode: 0644         
    block: |           
      * soft nofile 32768
      * hard nofile 32768
      * soft nproc 32768
      * hard nproc 32768
      root       soft    nproc     unlimited
      ams        -       nofile   64000
      atlas      -       nofile   64000
      druid      -       nofile   64000
      hive       -       nofile   64000
      infra-solr -       nofile   64000
      kms        -       nofile   64000
      knox       -       nofile   64000
      logsearch  -       nofile   64000
      ranger     -       nofile   64000
      spark      -       nofile   64000
      zeppelin   -       nofile   64000
      zookeeper  -       nofile   64000
    marker: "# {mark} ANSIBLE MANAGED BLOCK"                       
