---
# vars file for sftp-mockup-server
- sftp_users:
    - name: peter
      password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
      shell: False
      sftp_directories:
      - directory_only_for_peter1
      - directory_only_for_peter2
    - name: sally
      password: ""
      authorized: [sally.pub]
      home: /var/tmp/sally
      append: True
- sftp_directories:
  - imports
  - exports
  - { name: public, mode: 755 }
  - other