---
# tasks file for provision-resource-group
- name: Build {{ cloud_config.resource_group }} Resource Group
  azure_rm_resourcegroup:
    name: "{{ cloud_config.resource_group }}"
    location: "{{ cloud_config.location }}"
    state: present
    force: yes
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT_ID') }}" 
  ignore_errors: yes
    
