  //Jenkins pipeline to provision HDInsight infrastructure
    def azureSubscription = ""
    def inputSubscription = ""
    def skipRemainingStages = "true"

    pipeline {
    agent any
    parameters{
  false
    booleanParam(defaultValue: false, name: 'oozie_db', description: 'Provision an Oozie database')
        }

    stages {
    stage ('Git checkout and switch to Master') {
    steps {
    sh 'git checkout --track origin/mike'
    }
    }

    stage ('Create HDI environment configuration') {
    steps {
  withCredentials([azureServicePrincipal(credentialsId: "${env.CREDENTIAL_ID}" ,
                                                          subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                          clientIdVariable: 'AZURE_CLIENT_ID',
                                                          clientSecretVariable: 'AZURE_SECRET',
                                                          tenantIdVariable: 'AZURE_TENANT')]) {
                                                          ansiblePlaybook playbook: 'playbooks/create-new-environment.yml', skippedTags: 'dataproject'
  }
  }
  }

    stage ('Provision HDI Infrastructure') {
    steps {

  withCredentials([azureServicePrincipal(credentialsId: "${env.CREDENTIAL_ID}" ,
                                                          subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                          clientIdVariable: 'AZURE_CLIENT_ID',
                                                          clientSecretVariable: 'AZURE_SECRET',
                                                          tenantIdVariable: 'AZURE_TENANT')]) {
                                                          ansiblePlaybook extras: "-e @environments/dp-curation-q-dev/all", playbook: 'playbooks/provision-virtual-environment.yml', skippedTags: 'dataproject,hdi'
  }
  }
  }

  }
  }
