  //Jenkins pipeline to provision Hortonworks infrastructure
    def azureSubscription = ""
    def inputSubscription = ""
    def skipRemainingStages = "true"

    pipeline {
    agent any
    parameters{
    choice(name: 'subscription', choices: 'Project Azure governance testing', description: 'Subscription to provision')
    choice(name: 'ResourceGroup', choices: 'dp-ingestion-ifin-dev', description: 'Subscription to provision')
    choice(name: 'data_domain', choices: 'dp', description: 'this is the Data Domain')
    choice(name: 'resource_group_phase', choices: 'ingestion', description: 'Resourcegroup Phase')
    choice(name: 'project_name', choices: 'ifin', description: 'Project Name')
    choice(name: 'env_type', choices: 'dev', description: 'Environment type to provision')
    choice(name: 'nifi_nodes_count', choices: '1', description: 'Current Nifi Node count')
    choice(name: 'add_nifi_nodes', choices: 'Please select\n1\n2\n3\n4', description: 'choose the amount of nodes to add to the existing for Nifi cluster')
        string(name: 'nifi_installed', defaultValue: 'nifi is already installed' )
        }

    environment {
        master_project_name = "dp-ingestion-ifin-dev"
        job_type = "jenkinsfile_data.j2"
    }

    stages {

    stage ('Git checkout and switch to Master') {
    steps {
    sh 'git checkout --track origin/master'
    }
    }

    stage ('update all file') {
    steps {

  withCredentials([azureServicePrincipal(credentialsId: 'SPAzureGovernanceTesting',
                                                          subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                          clientIdVariable: 'AZURE_CLIENT_ID',
                                                          clientSecretVariable: 'AZURE_SECRET',
                                                          tenantIdVariable: 'AZURE_TENANT')]) {
                                                          ansiblePlaybook extras: "-e @environments/dp-ingestion-ifin-dev/all", playbook: 'playbooks/create-new-environment.yml', skippedTags: 'create,hdi'
  }
  }
  }

    stage ('Provision Infrastructure') {
    steps {

    withCredentials([azureServicePrincipal(credentialsId: 'SPAzureGovernanceTesting' ,
                                                            subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                            clientIdVariable: 'AZURE_CLIENT_ID',
                                                            clientSecretVariable: 'AZURE_SECRET',
                                                            tenantIdVariable: 'AZURE_TENANT')]) {
                                                            ansiblePlaybook extras: "-e @environments/dp-ingestion-ifin-dev/all", playbook: 'playbooks/provision-virtual-environment.yml', skippedTags: 'hdi'
  }
  }
  }
  }
  }
