---
# tasks file for calculate-vnet-prefix
- include_vars: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'application_name') }}-{{ lookup('env', 'env_type') }}/all"

- block:
  - name: Get list of VNET SDP INTERNAL peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_sdp_internal.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_sdp_internal.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_sdp_internal.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_internal_result  

  - name: Get list of VNET LIBERTY GLOBAL AD DOMAIN peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_ad_domain.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_ad_domain.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_ad_domain.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_ad_result

- name: Combine VNET AD DOMAIN and VNET INTERNAL peerings
  set_fact:
    peering_results: "{{ vnet_internal_result }},{{ vnet_ad_result }}"        

- name: delete file
  ignore_errors: yes
  file:
    state: absent
    path: "{{ lookup('env', 'WORKSPACE') }}/playbooks/roles/calculate-vnet-prefix/files/prefixfile"
 
- name: Ansible create file if it doesn't exist example
  ignore_errors: yes
  file:
    path: "{{ lookup('env', 'WORKSPACE') }}/playbooks/roles/calculate-vnet-prefix/files/prefixfile"
    state: touch

- name: debug vnet calc results\
  debug:
    msg: "{{ peering_results }}"        

- name: Distillate all subnet prexies already taken
  include_tasks: distillate-subnet-prexies.yml
  vars:
    remote_address_space: "{{ peering.remote_address_space }}"
  loop: "{{ peering_results.vnetpeerings }}"
  loop_control:
    loop_var: peering

- name: find next subnet prefix
  command: "python calculate_vnet_prefix.py"
  args:
    chdir: "{{ lookup('env', 'WORKSPACE') }}/playbooks/roles/calculate-vnet-prefix/files"
  register: newsubnetprefix

- name: "!!!! Calculated value "
  debug:
     msg: "{{ newsubnetprefix.stdout_lines[0] }}"

- name: replace anchore in all file of this data project
  replace:
    path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'application_name') }}-{{ lookup('env', 'env_type') }}/all"
    replace: "{{ newsubnetprefix.stdout_lines[0] }}"
    regexp: "VNET-ANCOR"

