---
# Add alle nifi nodes in special fact of this resource group
- set_fact: outer_loop="{{ item }}"

- name: Bedug Groups
  debug:
    var: groups

- name: Add nodes to hadoop-cluster and {{ outer_loop.host_group }} groups
  add_host:
    name: "{{ hostvars[local_loop].name }}"
    ansible_host: "{{ (outer_loop.public_ip|default(false)== true) | ternary(hostvars[local_loop].public_ip,hostvars[local_loop].private_ip) }}"
    ansible_user: "{{ cloud_config.admin_username|default('root') }}"
    ansible_ssh_private_key_file: "{{ cloud_config.ssh.sdp_admin_publickey }}"
    ansible_become_user: root
    groups: hadoop-cluster, {{ outer_loop.host_group }}
  loop_control:
    loop_var: local_loop
  when: outer_loop.count > '0'
  with_items: "{{ groups['all'] }}"


- name: Bedug Groups
  debug:
    var: "{{ hostvars[outer_loop] }}"
#  loop_control:
#    loop_var: vm_host
#  with_items: "{{ groups['all'] }}"
     
#- name: Add nodes to hadoop-cluster and {{ outer_loop.host_group }} groups
#  add_host:
#    name: "{{ outer_loop.ansible_hostname }}"
#    ansible_host: "{{ outer_loop.ansible_host }}"
#    ansible_user: "{{ cloud_config.admin_username|default('root') }}"
#    ansible_ssh_private_key_file: "{{ cloud_config.ssh.sdp_admin_publickey }}"
#    ansible_become_user: root
#    groups: hadoop-cluster
#  when: (outer_loop.tags.rolecount == 'nifi_worker' or outer_loop.tags.role == 'ambari_mgmt')

