---
# tasks file for create-vm
- name: Create NIC {{ functionality }} (with private IP only)
  azure_rm_networkinterface:
    name: q1
    resource_group: "{{ cloud_config.resource_group }}"
    #tags: "{{ cloud_config.tags }}"
    virtual_network_name: "{{ cloud_config.network.name }}"
    subnet_name: "{{ cloud_config.subnet.name }}"
    security_group_name: "{{ cloud_config.security_groups.name }}"
    ip_configurations:
      - name: "ipconfig-{{ cloud_config.project_name }}-{{ cloud_config.env_type }}-{{ functionality }}{{ number }}"
        primary: True