---
# tasks file for create-vm

- block:
    - name: Create NIC(s) (with private IP only)
      azure_rm_networkinterface:
        resource_group: "{{ cloud_config.resource_group }}"
        name: "nic-{{ cloud_config.name_project|default('') }}-{{ cloud_config.name_env|default('') }}-{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > '1') | ternary(local_loop,'') }}"
        virtual_network_name: "{{ cloud_config.network.name }}"
        subnet_name: "{{ cloud_config.subnet.name }}"
        security_group_name: "{{ outer_loop.security_group }}"
        ip_configurations:
          - name: "ipconfig-{{ cloud_config.name_project|default('') }}-{{ cloud_config.name_env|default('') }}-{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > '1') | ternary(local_loop,'') }}"
            primary: True
      loop_control:
        loop_var: local_loop
      with_sequence: count="{{ outer_loop.count }}" format=-%02x
      async: 1000
      poll: 0
      register: current_private_nics_async

    - name: Wait for NIC(s) to be built
      async_status:
        jid: "{{ local_loop.ansible_job_id }}"
      loop_control:
        loop_var: local_loop
      with_items: "{{ current_private_nics_async.results }}"
      register: current_private_nics
      until: current_private_nics.finished
      retries: 120
  when: not outer_loop.public_ip|default(false)|bool

- name: Create {{ outer_loop.host_group }} node(s)
  azure_rm_virtualmachine:
    resource_group: "{{ cloud_config.resource_group }}"
    storage_account_name: "{{ cloud_config.storage_account.name }}"
    name: "vm-{{ cloud_config.name_project|default('') }}-{{ cloud_config.name_env|default('') }}-{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > '1') | ternary(local_loop,'') }}"
    image:
      offer:  "{{ outer_loop.image.offer }}"
      publisher: "{{ outer_loop.image.publisher }}"
      sku: "{{ outer_loop.image.sku }}"
      version: "{{ outer_loop.image.version }}"
    vm_size: "{{ outer_loop.flavor }}"
    network_interface_names: "nic-{{ cloud_config.name_project|default('') }}-{{ cloud_config.name_env|default('') }}-{{ cluster_name }}-{{ outer_loop.host_group }}{{ (outer_loop.count > '1') | ternary(local_loop,'') }}"
    ssh_password_enabled: false
    admin_username: "{{ cloud_config.admin_username }}"
    ssh_public_keys:
      - path: "/home/{{ cloud_config.admin_username }}/.ssh/authorized_keys"
        key_data: "{{ lookup('file', cloud_config.ssh.publickey) }}"
    state: present
    tags:
      Cluster: "{{ cluster_name }}"
      Role: "{{ outer_loop.host_group }}"
      Group: "{{ cluster_name }}-{{ outer_loop.host_group }}"
  loop_control:
    loop_var: local_loop
  with_sequence: count="{{ outer_loop.count }}" format=-%02x
  async: 1000
  poll: 0
  register: current_nodes_async

- name: Wait for {{ outer_loop.host_group }} node(s) to be built
  async_status:
    jid: "{{ local_loop.ansible_job_id }}"
  loop_control:
    loop_var: local_loop
  with_items: "{{ current_nodes_async.results }}"
  register: current_nodes
  until: current_nodes.finished
  retries: 120
