---
# tasks file for provision-vm

- name: Create Nifi cluster vm's
  import_tasks: create-vm.yml
  vars:
    flavor: "{{ cloud_config.nifi.flavor }}"
    host_group: "nifi"
    count: 1
  when: cloud_config.nifi.provision

#- name: Create Kafaka mock-up vm
#  import_tasks: create-vm.yml
#  when: kafka.provision is succeeded
