---
# tasks file for provision-vm
- name: Create Nifi cluster vm's
  import_tasks: create-vm.yml
  vars:
    flavor: "{{ cloud_config.nifi.flavor }}"
    host_group: "nifi"
    number: "{{ local_loop }}"
  loop_control:
    loop_index: local_loop
  with_sequence: count="{{ count }}" format=-%02x
  when: cloud_config.nifi.provision