---
-  name: update ssh
   include_tasks: push_keys.yml
   vars:
     user_env: "{{ item.user_env }}"
     user: "{{ item.user }}"
     host_location: "{{ item.host_location }}"
   loop:
     - { user_env: "internal_jumpbox_admin", user: "sdp_admin", host_location: "internal" }
     - { user_env: "internal_jumpbox_user" , user: "sdp_user", host_location: "internal" }
     - { user_env: "external_jumpbox_admin", user: "sdp_admin", host_location: "external" }
     - { user_env: "external_jumpbox_user" , user: "sdp_user", host_location: "external" }

