---
- name: Copy script
  copy:
  src: public_keys
  dest: {{ directory }}
  mode: 755
  delegate_to: localhost

- name : List system keys (provision only our ansible user)
  local_action: "command find {{ directory }} -type f -path \"*/internal/*\""
  register: old_key_in
  become: false
  check_mode: no
  changed_when: false

- name : List system keys (provision only our ansible user)
  local_action: "command find {{ directory }} -type f -path \"*/external/*\""
  register: old_key_ex
  become: false
  check_mode: no
  changed_when: false

- name: Copy script
  copy:
  src: public_keys
  dest: {{ directory }}
  mode: 755
  delegate_to: localhost

- name : List system keys (provision only our ansible user)
  local_action: "command find {{ directory }} -type f -path \"*/external/*\""
  register: new_key_ex
  become: false
  check_mode: no
  changed_when: false

- name : List system keys (provision only our ansible user)
  local_action: "command find {{ directory }} -type f -path \"*/internal/*\""
  register: new_key_in
  become: false
  check_mode: no
  changed_when: false

- name: create matched and unmatched lists
    new_ex: "{{ new_key_ex.stdout_lines|list | difference(old_key_ex.stdout_lines|list)) | first }}"
    new_in: "{{ new_key_in.stdout_lines|list | difference(old_key_in.stdout_lines|list)) | first }}"
    old_in: "{{ old_key_in.stdout_lines|list | difference(new_key_in.stdout_lines|list)) | first }}"
    old_ex: "{{ old_key_ex.stdout_lines|list | difference(new_key_ex.stdout_lines|list)) | first }}"

- name: Delete unmatched keys for {{ public_key_user }}
  authorized_key:
    user: "{{ lookup('file', item) }}"
    state: absent
    key: "{{ lookup('file', item) }}"
  with_items: "{{ old_ex }}"
  delegate_to: external

- name: Delete unmatched keys for {{ public_key_user }}
  authorized_key:
    user: "{{ lookup('file', item) }}"
    state: absent
    key: "{{ lookup('file', item) }}"
  with_items: "{{ old_in }}"
  delegate_to: internal

- name: Add matched keys for internal
  authorized_key:
    user: "{{ lookup('file', item) }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ new_in }}"
  delegate_to: internal

- name: Add matched keys for internal
  authorized_key:
    user: "{{ lookup('file', item) }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ new_ex }}"
  delegate_to: external
