---
# tasks file for provision-vnet
- name: Create {{ subnet.name }} Subnet
  azure_rm_subnet:
    resource_group: "{{ cloud_config.resource_group }}"
    virtual_network_name: "{{ cloud_config.network.name }}"
    name: "{{ subnet.name }}"
    address_prefix_cidr : "{{ subnet.address_prefix }}"
    security_group:
      name: "{{ cloud_config.security_groups.name }}"
    service_endpoints: "{{ service_endpoints }}"
