---
# tasks file for provision-vnet
- name: Create {{ cloud_config.network.name }} Virtual Network
  azure_rm_virtualnetwork:
    resource_group: "{{ cloud_config.resource_group }}"
    name: "{{ cloud_config.network.name }}"
    tags: "{{ cloud_config.tags }}"
    address_prefixes_cidr: "{{ cloud_config.network.address_prefix }}"
  register: vnet_result
