---
# tasks file for provision-vnet
- name: Create {{ cloud_config.network.name }} Virtual Network
  azure_rm_virtualnetwork:
    resource_group: "{{ cloud_config.resource_group }}"
    name: "{{ cloud_config.network.name }}"
    tags: "{{ cloud_config.tags }}"
    address_prefixes_cidr: "{{ cloud_config.network.address_prefix }}"
  register: vnet_result

- name: Create "{{ cloud_config.subnet.name }}" Subnet
  azure_rm_subnet:
    resource_group: "{{ cloud_config.resource_group }}"
    virtual_network_name: "{{ cloud_config.network.name }}"
    name: "{{ subnet.name }}"
    address_prefix_cidr : "{{ subnet.address_prefix }}"
    security_group:
      name: "{{ cloud_config.security_groups.name }}"
  loop: "{{ cloud_config.subnet }}"
  loop_control:
    loop_var: subnet        
  tags: hdi 

- name: Create "{{ cloud_config.subnet.name }}" Subnet
  #azure_rm_subnet:
  # resource_group: "{{ cloud_config.resource_group }}"
  # virtual_network_name: "{{ cloud_config.network.name }}"
  # name: "{{ subnet.name }}"
  # address_prefix_cidr : "{{ subnet_item.address_prefix }}"
  # security_group:
  #   name: "{{ cloud_config.security_groups.name }}"
  loop: "{{ cloud_config.subnet }}"
  loop_control:
    loop_var: subnet      
  tags: dataproject
  debug:
    msg: "{{ subnet_item[0] }}"        
