---
# tasks file for provision-vnet
- name: Create Virtual Network
  include_tasks: create-vnet.yml

- name: Create HDI Subnets
  include_tasks: create-subnet.yml
  loop: "{{ cloud_config.subnet }}"
  loop_control:
    loop_var: subnet
  tags: hdi 

- name: Create HDF Subnet
  include_tasks: create-subnet.yml
  loop: "{{ cloud_config.subnet }}"
  loop_control:
    loop_var: subnet
    index_var: index
  when: index == 0 
  tags: dataproject  
