  //Jenkins pipeline to provision HDInsight infrastructure
    def azureSubscription = ""
    def inputSubscription = ""
    def skipRemainingStages = "true"

    pipeline {
    agent any
    parameters{
    booleanParam(defaultValue: false, name: 'oozie_db', description: 'Provision an Oozie database')
      booleanParam(defaultValue: false, name: 'hive_db', description: 'Provision a Hive database')
      booleanParam(defaultValue: false, name: 'ranger_db', description: 'Provision a Ranger database')
    }

    stages {
    stage ('Git checkout and switch to Master') {
    steps {
    sh 'git checkout --track origin/mike'
    }
    }

    stage ('Create HDI environment configuration') {
    steps {
  withCredentials([azureServicePrincipal(credentialsId: 'SPAzureGovernanceTesting' ,
                                                          subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                          clientIdVariable: 'AZURE_CLIENT_ID',
                                                          clientSecretVariable: 'AZURE_SECRET',
                                                          tenantIdVariable: 'AZURE_TENANT')]) {
                                                          ansiblePlaybook playbook: 'playbooks/maintain-environment.yml', skippedTags: 'dataproject,create'
  }
  }
  }
/*
    stage ('Provision HDI Infrastructure') {
    steps {

  withCredentials([azureServicePrincipal(credentialsId: 'SPAzureGovernanceTesting' ,
                                                          subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                          clientIdVariable: 'AZURE_CLIENT_ID',
                                                          clientSecretVariable: 'AZURE_SECRET',
                                                          tenantIdVariable: 'AZURE_TENANT')]) {
                                                          ansiblePlaybook extras: "-e @environments/dp-curation-test-dev/all", playbook: 'playbooks/provision-virtual-environment.yml', skippedTags: 'dataproject,hdi'
  }
  }
  }
*/
  }
  }
