---
# tasks file for provision-roleassignment

- name: Create a role assignment
  vars:
    managed_identity: "mi-{{ cloud_config.resource_group_phase }}-{{ cloud_config.project_name }}-{{ cloud_config.env_type }}"
  azure_rm_roleassignment:
    scope: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourcegroups/dp-integration-oreo-anupi-sit-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ managed_identity }}"
    assignee_object_id: "{{ cloud_config.sp_object_id }}"
    role_definition_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/providers/Microsoft.Authorization/roleDefinitions/{{item}}"
  with_items: "{{ cloud_config.role_definition_id }}"
  tags: hdi
