---
# tasks file for provision-roleassignment

- name: Create a role assignment for ManagedIdentity
  vars:
    managed_identity: "mi-{{ cloud_config.hdi_cluster.short_name }}"
  azure_rm_roleassignment:
    scope: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourcegroups/{{ cloud_config.resource_group }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ managed_identity }}"
    assignee_object_id: "{{ cloud_config.adls_service_principal_objectid }}"
    role_definition_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/providers/Microsoft.Authorization/roleDefinitions/{{item}}"
    state: present
  with_items: "{{ cloud_config.role_definition_id }}"
  tags: hdi

#- name: Create a role assignment for AAD
#  azure_rm_roleassignment:
#    scope: "{{ cloud_config.ad_domain_service.resource_path }}"
#    assignee_object_id: "{{ identity.principalId}}" #the value needs to be fetched with correct jinja filter (check on managed identity role)
#    role_definition_id: "{{ cloud_config.ad_role_definition_id }}"
#    state: present
