---
# tasks file for provision-peering
      # This task is ignorbel because may be current user have no sufficent rights to create this peering
    - name: Create virtual network peering with {{ peering.remote_resource_group }}
      azure_rm_virtualnetworkpeering:
        resource_group: "{{ cloud_config.resource_group }}"
        virtual_network: "{{ cloud_config.network.name }}"
        name: "{{ peering.initial_peering_name }}"
        remote_virtual_network:
          resource_group: "{{ peering.remote_resource_group }}"
          name: "{{ peering.remote_virtual_network }}"
        allow_virtual_network_access: false
        allow_forwarded_traffic: true
      ignore_errors: yes
