---
# tasks file for provision-peering
      # This task is ignorbel because may be current user have no sufficent rights to create this peering
- name: Initial virtual network peering with {{ cloud_config.peering.access_resource_group }}
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ cloud_config.resource_group }}"
    virtual_network: "{{ cloud_config.network.name }}"
    name: "{{ cloud_config.peering.initial_peering_name }}"
    remote_virtual_network:
      resource_group: "{{ cloud_config.peering.access_resource_group }}"
      name: "{{ cloud_config.peering.access_virtual_network }}"
  ignore_errors: yes

- name: Connect virtual network peering with {{ cloud_config.peering.access_resource_group }}
  azure_rm_virtualnetworkpeering:
    subscription_id: "{{ cloud_config.peering.access_rg_id }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"        
    resource_group: "{{ cloud_config.peering.access_resource_group }}"
    name: "{{ cloud_config.peering.connect_peering_name }}"
    virtual_network: "{{ cloud_config.peering.access_virtual_network }}"
    remote_virtual_network:
            #  subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
            #tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
            # secret: "{{ lookup('env', 'AZURE_SECRET') }}"
            # client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      resource_group: "{{ cloud_config.resource_group }}"
      name: "{{ cloud_config.network.name }}"
  ignore_errors: yes
