pipeline {
    agent any
    parameters{
            choice(name: 'Environment', choices: 'Please select\nDEV\nSIT\nUAT\nPRD', description: 'Environment type to provision')
       }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Whitelist ip') {
                environment {
                    CLOUD_TO_USE = "${Cloud}"
                }
                steps {
                    script {
                        withCredentials([azureServicePrincipal(credentialsId: '1683b46e-b612-4f6d-a717-9baed4b0dffb',
                                                  subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                                  clientIdVariable: 'AZURE_CLIENT_ID',
                                                  clientSecretVariable: 'AZURE_SECRET',
                                                  tenantIdVariable: 'AZURE_TENANT')]) {
                         dir("${WORKSPACE}") {
                            ansiblePlaybook([
                                    playbook    : '@playbooks/provision-virtual-environment.yml',
                                    installation: 'ansible',
                                    extras: "--extra-vars 'all'"
                            ])
                         //ansiblePlaybook playbook: './playbooks/whitelist_ips.yml' extra-vars: '.grantaccess/testvar-rg'
                        }
                    }
                }
            }
        }
        stage('Post Deploy') {
            steps {
                sh 'echo Executeeeeeeeeeee 2'
            }
        }
    }