---
# tasks file for provision-sql-server
- name: Create SQL Database
  azure_rm_sqldatabase:
    resource_group: "{{ cloud_config.resource_group }}"
    server_name: "dbsqlserver{{ cloud_config.resource_group_phase }}{{ cloud_config.project_name }}{{ cloud_config.env_type }}"
    name: "dbsql{{ cloud_config.resource_group_phase }}{{ cloud_config.project_name }}{{ cloud_config.env_type }}{{ item.name }}"
    location: "{{ cloud_config.location }}"
    create_mode: default
    edition: basic
