---
# tasks file for provision-sql-server
  - name: Create (or update) SQL Server
    azure_rm_sqlserver:
      resource_group: "{{ cloud_config.resource_group }}"
      name: "dbsqlserver{{ cloud_config.resource_group_phase }}{{ cloud_config.project_name }}{{ cloud_config.env_type }}"
      location: "{{ cloud_config.location }}"
      admin_username: "{{ cloud_config.env_type }}-admin"
      admin_password: "{{ password }}"
