---
# tasks file for provision-sql-server

- name: Provision SQL Server

  - block:
     - name: Create (or update) SQL Server
       azure_rm_sqlserver:
         resource_group: "{{ cloud_config.resource_group }}"
         name: "dbsqlserver{{ resource_group_phase }}{{ project_name }}{{ env_type }}{{ number }}"
         location: "{{ cloud_config.location }}"
         admin_username: "{{ env_type }}-admin"
         admin_password: "{{ cloud_config.sql_db_pwd }}"
  
     - name: Create SQL Database
       azure_rm_sqldatabase:
         resource_group: "{{ cloud_config.resource_group }}"
         server_name: "dbsqlserver{{ resource_group_phase }}{{ project_name }}{{ env_type }}{{ number }}"
         name: "dbsql{{ resource_group_phase }}{{ project_name }}{{ env_type }}{{ item.name }}"
         location: "{{ cloud_config.location }}"
         edition: basic
       when: item.optional
       with_items: "{{ cloud_config.sql_db }}"
     when: cloud_config.sql_server
