---
# tasks file for provision-sql-server
- name: Generate password
  include_role: 
    name: azure-keyvault
    tasks_from: generate-secret.yml
    
- block:
  - name: Create SQL Server
    include_tasks: create-sqlserver.yml 
  
  - name: Store password
    include_role:
      name: azure-keyvault
      tasks_from: create-secret.yml
    vars:
      secret_name: "dbsqlserver{{ cloud_config.resource_group_phase }}{{ cloud_config.project_name }}{{ cloud_config.env_type }}-db-pwd"

  - name: Create SQL Database 
    include_tasks: create-sqldatabase.yml
    when: item.provision
    loop: "{{ cloud_config.sql_db }}"
