---

-  name: update all file
   include_tasks: update_all_file.yml
   vars:
     reg: "{{ item.regex }}"
   when: item.condition
   loop:
      - { regex: '(?<=oozie.\n)(\s*\w*:\s*)false', condition: "{{ lookup('env', 'oozie_db') }}" }
      - { regex: '(?<=hive.\n)(\s*\w*:\s*)false', condition: "{{ lookup('env', 'hive_db') }}" }
      - { regex: '(?<=ranger.\n)(\s*\w*:\s*)false', condition: "{{ lookup('env', 'ranger_db') }}" }
      - { regex: '(?<=nifi.\n)(\s*\w*:\s)false', condition : "{{ lookup('env', 'nifi') }}" }
      - { regex: '(?<=sftp.\n)(\s*\w*:\s)false', condition: "{{ lookup('env', 'sftp') }}" }
      - { regex: '(?<=oracle.\n)(\s*\w*:\s)false', condition: "{{ lookup('env', 'oracle') }}" }


#-  name: update jenkinsfile
#   include_tasks: update_jenkinsfile.yml
#   vars:
#      reg: "{{ item.regex }}"
#   when: item.condition
#   loop:
#      - { regex: 'booleanParam.defaultValue: false, name: .oozie., description: .Provision an Oozie database..', condition: "{{  cloud_config.sql_db[0].provision }}" }
#      - { regex: 'booleanParam.defaultValue: false, name: .hive_db., description: .Provision a Hive database..', condition: "{{  cloud_config.sql_db[1].provision }}" }
#      - { regex: 'booleanParam.defaultValue: false, name: .ranger_db., description: .Provision a Ranger database..', condition: "{{  cloud_config.sql_db[2].provision }}" }
#      - { regex: 'booleanParam.defaultValue: false, name: .sftp., description: .Provision a SFTP mockup server..', condition: "{{ cloud_config.mockup.sftp.provision }}" }
#      - { regex: 'booleanParam(defaultValue: false, name: .nifi., description: .Provision a NIFI cluster..', condition: "{{ cloud_config.nifi.provision }}" }
#      - { regex: 'booleanParam.defaultValue: false, name: .oracle., description: .Provision a oracle mockup db..', condition: "{{ cloud_config.mockup.oracle.provision }}" }








