---
- name: update all file true false status of oracle kaftka etc
  replace:
    path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ cloud_config.master_project_name }}/all"
    replace: '\g<1>true'
    regexp: '(?<={{ item.name }}.\n)(\s*\w*:\s)false'
    with_items:
      - { name: 'oozie'}
    #with_items:
     # - { regex: '(?<=nifi.\n)\s*\w*:\s*(false)', condition : "{{ lookup('env', 'nifi') | default('false', true) }}" }
     # - { regex: '(?<=sftp.\n)\s*\w*:\s*(false)', condition: "{{ lookup('env', 'sftp') | default('false', true) }}" }
     # - { regex: '(?<=oracle.\n)\s*\w*:\s*(false)', condition: "{{ lookup('env', 'oracle') | default('false', true) }}" }
     # - { regex: '(?<=oozie.\n)\s*\w*:\s*(false)', condition: "{{ lookup('env', 'oozie_db') | default('false', true) }}" }
     # - { regex: '(?<=hive.\n)\s*\w*:\s*(false)', condition: "{{ lookup('env', 'hive_db') | default('false', true) }}" }
     # - { regex: '(?<=ranger.\n)\s*\w*:\s*(false)', condition: "{{ lookup('env', 'ranger_db') | default('false', true) }}" }
