---

-  name: Validate the sudoers file before saving
   lineinfile:
     path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/Jenkinsfile"
     state: absent
     regexp: 'booleanParam.defaultValue: false, name: 'oozie_db', description: 'Provision an Oozie database'.'
   when: cloud_config.sql_db.provision[0]
