---

-  name: Validate the sudoers file before saving
   lineinfile:
     path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/Jenkinsfile"
     state: absent
     regexp: "{ reg }"
