---

-  name: delete unnescescary lines in jenkinsfile
   lineinfile:
     path: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/Jenkinsfile"
     state: present
     regexp: "{{ reg }}"
     line: "{{ line }}"
