---
# tasks file for provision-security-groups
- name: Create (or update) security groups
  azure_rm_securitygroup:
    resource_group: "{{ cloud_config.resource_group }}"
    name: "{{ cloud_config.security_groups.name }}"
    tags: "{{ cloud_config.tags | default(omit) }}"
    rules: "{{ inbound_rules | default(omit) }}"
