---

  - include_vars: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/all"


  - name: check uniqueness of VNET SDP INTERNAL peerings
    include_tasks: test_unique_vnet_peering_name.yml
    vars:
      rs_group: "{{ loop_local.remote_resource_group  }}"
      vn: "{{ loop_local.remote_virtual_network }}"
      sub_id: "{{ loop_local.remote_subscription_id }}"
      register: "{{ {{ loop_local }}-fact }} }}"
      fail_loop: "{{ {{ register }}.vnetpeerings }}"
    loop_control:
      loop_var: loop_local
    with_items:
      - "{{ cloud_config.peering.vnet_sdp_internal }}"
      - "{{ cloud_config.peering.vnet_ad_domain }}"
      - "{{ cloud_config.peering.vnet_sdp_external }}"
      - "{{ cloud_config.peering.vnet_cicd_prd }}"

  - name: Get list of VNET SDP INTERNAL peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_sdp_internal.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_sdp_internal.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_sdp_internal.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_internal_result

  - name: Get list of VNET AD Domain peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_ad_domain.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_ad_domain.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_ad_domain.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_ad_result

  - name: Get list of VNET SDP external peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_sdp_external.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_sdp_external.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_sdp_external.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_external

  - name: Get list of VNET CICD prd peerings
    azure_rm_virtualnetworkpeering_facts:
      resource_group: "{{ cloud_config.peering.vnet_cicd_prd.remote_resource_group }}"
      virtual_network: "{{ cloud_config.peering.vnet_cicd_prd.remote_virtual_network }}"
      subscription_id: "{{ cloud_config.peering.vnet_cicd_prd.remote_subscription_id }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    register: vnet_cicd

  - fail:
      msg: The vnet name exists in vnet_sdp_internal
    when:  item.name == cloud_config.peering.vnet_sdp_internal.connect_peering_name
    loop: "{{ vnet_internal_result.vnetpeerings }}"

  - fail:
      msg: The vnet name exists in Ad Domain
    when:  item.name == cloud_config.peering.vnet_ad_domain.connect_peering_name
    loop: "{{ vnet_ad_result.vnetpeerings }}"

  - fail:
      msg: The resource_group already exists!
    when:  item.name == cloud_config.peering.vnet_cicd_prd.connect_peering_name
    loop: "{{ vnet_cicd.vnetpeerings }}"

  - fail:
      msg: The vnet name exists in vnet_sdp_external
    when:  item.name == cloud_config.peering.vnet_sdp_external.connect_peering_name
    loop: "{{ vnet_external.vnetpeerings }}"

  - fail:
      msg: The resource_group is not according to the namespace conventions ( 24 > 3 characters)
    when: rg_name_test | length > 24

  - name: Get facts for all resource groups
    azure_rm_resourcegroup_facts:
    register: azure_resource_groups

  - fail:
      msg: The resource_group already exists!
    when:  item.name == rg_name_test
    loop: "{{ azure_resource_groups.resourcegroups }}"
