---
- name: Add public keys
  hosts: internal
  connection: ssh
  gather_facts: false
  remote_user: sdp-admin
  roles:
    - add-public-keys
#  loop:
#    - { user_env: "internal_jumpbox_admin", user: "sdp_admin", host_location: "internal" }
#    - { user_env: "internal_jumpbox_user" , user: "sdp_user", host_location: "internal" }
#    - { user_env: "external_jumpbox_admin", user: "sdp_admin", host_location: "10.0.1.4 " }
#    - { user_env: "external_jumpbox_user" , user: "sdp_user", host_location: "10.0.1.4 " }
#  hosts: "{{ item.host_location }}"
#  remote_user: "{{ item.user }}"
