- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'master_project_name') }}"

  roles:
    - create-jenkins-project
    - create-environment-configuration
    - validation
    - push-files-to-repo  
