- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'env_type') }}"

    - name: Get list of VNET LIBERTY GLOBAL AD DOMAIN peerings
      azure_rm_virtualnetworkpeering_facts:
        resource_group: access-sdp-jumpbox-rg
        virtual_network: vnet-sdp-internal
        client_id: 132d0b25-06e1-4a54-95fd-410d9c18e915
        secret: vgSQ?.80?PqZUNOh]kVXxYDXIBAnId35
        tenant: 98fbb231-4a93-4dee-85a8-9c286ddfb92d
      register: vnet

    - debug:
        msg: "{{ vnet }}"

    - fail:
        msg: The resource_group is not according to the namespace conventions ( 24 > 3 characters)
      when: master_project_name | length > 24

    - name: Get facts for all resource groups
      azure_rm_resourcegroup_facts:
      register: azure_resource_groups

    - debug:
        msg: "{{ azure_resource_groups }}"

    - fail:
        msg: The resource_group already exists!
      loop: "{{ azure_resource_groups.resourcegroups }}"
      when:  item.name == master_project_name




