- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'env_type') }}"
  tasks:
    - include role:
        name: "{{ role }}"
      loop:
        - create-jenkins-project
        - create-environment-configuration
        - validation
        - push-files-to-repo
      loop_control:
        loop_var: role
      tags: create

    - include role:
        name: "{{ role }}"
      loop:
        - maintain-environment-files
        - push-files-to-repo
      loop_control:
        loop_var: role
      tags: maintain



