---
- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'master_project_name') }}"

  tasks:
    - include_role:
        name: "{{ role }}"
      loop:
        - create-jenkins-project
        - create-environment-configuration
        - validation
        - push-files-to-repo
      loop_control:
        loop_var: role
      tags: create

    - include_role:
        name: "{{ role }}"
      loop:
        - maintain-environment-files
        - push-files-to-repo
      loop_control:
        loop_var: role
      tags: maintain
