- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_resource_groupname: "{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'application_name') }}-{{ lookup('env', 'env_type') }}-rg"

    - debug:
        msg: "{{ master_resource_groupname }}"

    - fail:
        msg: The resource_group is not according to the namespace conventions ( 24 > 3 characters)
      when: master_resource_groupname | length > 24

    - name: Get facts for all resource groups
      azure_rm_resourcegroup_facts:
      register: azure_resource_groups

    - debug:
        msg: "{{ azure_resource_groups }}"

    - fail:
        msg: The resource_group already exists!
      when:  item.name != master_resource_groupname
      loop: "{{ azure_resource_groups.azure_resourcegroups }}"
  
#  roles:

#    - create-jenkins-project
#    - create-environment-configuration
#    - push-files-to-repo
