- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'env_type') }}"

  roles:
# This role needs to be further developed
    - create-jenkins-project
#    - create-environment-configuration
#    - validation
    - push-files-to-repo
