- name: Create new environment
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: "set resource groupname"
      set_fact:
        master_project_name: "{{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'env_type') }}"

    - name: Get facts for all virtual networks
      azure_rm_virtualnetwork_facts:
        resource_group: "{{ master_project_name }}"
      register: azure_vnets

    - debug:
        msg: "{{ azure_vnets }}"

    - debug:
        msg: "{{ master_project_name }}"

    - fail:
        msg: The resource_group is not according to the namespace conventions ( 24 > 3 characters)
      when: master_project_name | length > 24

    - name: Get facts for all resource groups
      azure_rm_resourcegroup_facts:
      register: azure_resource_groups

    - debug:
        msg: "{{ azure_resource_groups }}"

    - fail:
        msg: The resource_group already exists!
      loop: "{{ azure_resource_groups.resourcegroups }}"
      when:  item.name == master_project_name

  roles:
    - create-jenkins-project
    - create-environment-configuration
    - push-files-to-repo



