---
- name: Install Software of Data cluster
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: yes

# Execute install_os_packages task on all vms
- hosts: all
  roles:
  - install_os_packages

- import_playbook: set-host-groups.yml

- import_playbook: sftp-mockup-server.yml
  when: cloud_config.mockup.sftp.provision

- import_playbook: kafka-mockup-server.yml
  when: cloud_config.mockup.kafka.provision

- import_playbook: oracle-mockup-db.yml
  when: cloud_config.mockup.oracle.provision
