---
- name: Install Software of Data cluster
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: yes
   
- import_playbook: install-sftp-mockup-server.yml
  when: hostvars[inventory_hostname]['tags']['role'] == 'sftp_mockup'