---
- name: Install Software of Data cluster
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: yes

# Execute common task on all vms
  roles:
    - common

- import_playbook: install-ambari-cluster.yml
  when: cloud_config.nifi.provision and hostvars[inventory_hostname]['tags']['role'] == 'nifi'

- import_playbook: sftp-mockup-server.yml
  when: cloud_config.mockup.sftp.provision and hostvars[inventory_hostname]['tags']['role'] == 'sftp_mockup'

- import_playbook: kafka-mockup-server.yml
  when: cloud_config.mockup.kafka.provision and hostvars[inventory_hostname]['tags']['role'] == 'kafka_mockup'