---
#Start point of provisioning virtual environment
#- import_playbook: "set-azure-credentials.yml"
- name: Provision virtual environment
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - provision-resource-group
    - provision-security-groups
    - provision-vnet
    - provision-peering      
  block:
     roles:
       - provision-storageaccount
       - provision-vm
     tags: dataproject   
    
  block: 
    roles:
      - provision-sqlserver
    tags: hdi
