---
#Start point of provisioning virtual environment
#- import_playbook: "set-azure-credentials.yml"
- name: Provision virtual environment
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - block:
      - include_role:
        provision-storageaccount
        provision-vm
      tags: dataproject   
    
    - block: 
      - include_role:
        provision-sqlserver
      tags: hdi
    - include_role:
      provision-vnet
      provision-peering  
