#Start point of provisioning virtual environment
#- import_playbook: "set-azure-credentials.yml"
- name: Provision virtual environment
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: provision-resource-group
    - role: provision-storageaccount
    - role: provision-security-groups
    - role: provision-vnet
    - role: provision-peering
    - role: provision-vm
      tags: dataproject
    - role: provision-sqlserver
      tags: hdi  
