#Start point of provisioning virtual environment
#- import_playbook: "set-azure-credentials.yml"
- name: Provision virtual environment
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: rovision-resource-group
    - role: provision-security-groups
    - role: provision-vnet
    - role: provision-peering  
    
    - block:
      - role: provision-storageaccount
      - role: provision-vm
      tags: dataproject

    block:
      - role: provision-sqlserver
      tags: hdi  
