---   
# Distribute host to different hostgroups to further installation
- name: Create the required hosts groups
  hosts: all
  gather_facts: False
  
  tasks: 
  - name: Add nodes to the hadoopcluster group and groups representing the host_groups
    add_host:
      name: "{{ hostvars[item].ansible_host }}"
      groups: "{% if hostvars[item].tags.role == 'nifi_worker' %}hadoopcluster{% elif hostvars[item].tags.role == 'ambari_mgmt' %}ambariserver{% elif hostvars[item].tags.role == 'kafka' %}kafka{% elif hostvars[item].tags.role == 'sftp' %}sftp{% endif %}"
      ansible_host: "{{ hostvars[item].private_ipv4_addresses }}"
      ansible_user: "{{ cloud_config.admin_username|default('root') }}"
      ansible_ssh_private_key_file: "{{ cloud_config.ssh.sdp_admin_publickey }}"
      ansible_become_user: sdp_admin
    with_items: "{{ ansible_play_hosts_all }}"

  - name: Show groups
    debug:
      msg: "{{ groups['item']|length }}"
    with_items: "{{ groups }}"