---   
# Distribute host to different hostgroups to further installation
- name: Create the required hosts groups
  hosts: localhost
  gather_facts: False

  tasks:
  - name: check hosts
    debug:
      var: hostvars[inventory_hostname]

  - name: Add nodes to the hadoopcluster group and groups representing the host_groups
    add_host:
      name: "{{ hostvars[item].inventory_hostname }}"
      groups: "{% if hostvars[item].tags.role == 'nifi_worker' %}hdfmanagement{% elif hostvars[item].tags.role == 'ambari_mgmt' %}hdfworker{% elif hostvars[item].tags.role == 'kafka_mockup' %}kafka{% elif hostvars[item].tags.role == 'sftp_mockup' %}sftp{% elif hostvars[item].tags.role == 'oracle_mockup' %}oracle{% endif %}"
      tags: "{{ hostvars[item].tags }}"
      role: hostvars[item].tags.role
    with_items: "{{ ansible_play_hosts_all }}"

