---   
# Distribute host to different hostgroups to further installation
- name: Create the required hosts groups
  hosts: all
  gather_facts: False
  
  tasks: 
  - name: Add nodes to the hadoopcluster group and groups representing the host_groups
    add_host:
      name: "{{ hostvars[item].inventory_hostname }}"
      groups: "{% if hostvars[item].tags.role == 'nifi_worker' %}hadoopcluster{% elif hostvars[item].tags.role == 'ambari_mgmt' %}ambariserver{% elif hostvars[item].tags.role == 'kafka_mockup' %}kafka{% elif hostvars[item].tags.role == 'sftp_mockup' %}sftp{% endif %}"
      tags: "{{ hostvars[item].tags }}"
      role: hostvars[item].tags.role
    with_items: "{{ ansible_play_hosts_all }}"

