---
- name: Push generated file to git repo
  shell: |
      #git checkout --track origin/master
      git add -A 
      git commit -m "Create environment {{ lookup('env', 'data_domain') }}-{{ lookup('env', 'resource_group_phase') }}-{{ lookup('env', 'project_name') }}-{{ lookup('env', 'application_name') }}-{{ lookup('env', 'env_type') }}"
      git push origin master
  args:
    chdir: "{{ lookup('env', 'WORKSPACE') }}"
