---
- name: Push generated file to git repo
  shell: |
      git add -A 
      git commit -m "Create environment {{ master_project_name }}"
      git push 
  args:
    chdir: "{{ lookup('env', 'WORKSPACE') }}"
