---
  - name: Create project directory structure
    file:
        path: "{{ jenkins_job_directory }}/{{ data_domain }}-{{ resource_group_phase }}-{{ project_name }}-{{ application_name }}-{{ env_type }}"
        state: directory
        mode: 0755
        owner: "{{ lookup('env', 'USER') }}"
#        group: "{{ lookup('env', 'GROUP') }}"