---
- name: Create Jenkins file
  template:
    dest: "{{ lookup('env', 'WORKSPACE') }}/environments/{{ master_project_name }}/Jenkinsfile"
    src: Jenkinsfile.j2
    force: yes 
    output_encoding: utf-8
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
