---
  - name: Create Jenkins job
    jenkins_job:
      config: "{{ lookup('template', 'templates/config.j2') }}"
      name: "{{ lookup('env', 'project_name') }}"
      token: "{{ jenkins_token }}" 
      url: "{{ jenkins_api }}/job/CICD%20Automation"
      user: "{{ jenkins_user }}"

