---
- name: Create project config.xml
  template:
      dest: "../environments/{{ project_name }}/all.yml"
      src: all.j2
      force: yes 
#      owner: undefined # not required. Name of ddthe user that should own the file/directory, as would be fed to I(chown).
#      group: undefined # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
      output_encoding: utf-8 # not required. Overrides the encoding used to write the template file defined by C(dest).,It defaults to C('utf-8'), but any encoding supported by python can be used.,The source template file must always be encoded using C('utf-8'), for homogeneity.
      mode: 0644
