---
# tasks file for provision-security-groups
- name: Create security groups
  azure_rm_securitygroup:
      resource_group: "{{ cloud_config.resource_group }}"
      name: "{{ cloud_config.security_groups.name }}"
      #rules:
      #   - name: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.name }}"
      #      protocol: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.protocol }}"
      #      priority: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.priority }}"
      #      source_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.source }}"
      #      destination_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.destination }}"
      #      destination_port_range: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.port }}"
            # Below rule is not working yet. Waiting for updated module to include the ICMP protocol
            # - name: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.name }}"
            #protocol: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.protocol }}"
            #priority: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.priority }}"
            #source_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.source }}"
            #destination_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.destination }}"    
            #    - name: "{{ cloud_config.security_groups.rules.inbound.allow_ping.name }}"
            #protocol: "{{ cloud_config.security_groups.rules.inbound.allow_ping.protocol }}"
            #priority: "{{ cloud_config.security_groups.rules.inbound.allow_ping.priority }}"
            #source_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_ping.source }}"
            #destination_address_prefix: "{{ cloud_config.security_groups.rules.inbound.allow_ping.destination }}"
            #destination_port_range: "{{ cloud_config.security_groups.rules.inbound.allow_ping.port }}"
