---
# tasks file for provision-security-groups
- name: Create HDI security group
  include_tasks: create-nsg.yml
  vars:
    inbound_rules: 
      - name: "{{ inbound_rule.name }}"
        protocol: "{{ inbound_rule.protocol }}"
        priority: "{{ inbound_rule.priority }}"
        source_address_prefix: "{{ inbound_rule.source }}"
        destination_address_prefix: "{{ inbound_rule.destination }}"
        destination_port_range: "{{ inbound_rule.port }}"
  loop: "{{ cloud_config.security_groups.rules.inbound }}"
  loop_control:
    loop_var: inbound_rule
  tags: hdi

- name: Whitelist IP's
  include_tasks: create-nsg.yml
  vars:
    inbound_rules: 
      - name: "{{ inbound_rule.name }}"
        protocol: "{{ inbound_rule.protocol }}"
        priority: "{{ inbound_rule.priority }}"
        source_address_prefix: "{{ whitelist }}"
        destination_address_prefix: "{{ inbound_rule.destination }}"
        destination_port_range: "{{ inbound_rule.port }}"
  loop: "{{ cloud_config.security_groups.rules.inbound[0] }}"
  loop_control:
    loop_var: inbound_rule
  tags: hdi

    
- name: Create Data Project security group
  include_tasks: create-nsg.yml
