---
# tasks file for provision-security-groups
- name: Create security groups
  azure_rm_securitygroup:
      resource_group: "{{ cloud_config.resource_group }}"
      name: "{{ cloud_config.security_groups.name }}"
      rules:
          - name: "AllowPort_{{ cloud_config.security_groups.name }}"
            protocol: Tcp
            destination_port_range: "{{ cloud_config.security_groups.port }}"
            access: Allow
            direction: Inbound
            priority: 101
