---
# tasks file for provision-security-groups
- name: Create security groups
  azure_rm_securitygroup:
      resource_group: "{{ cloud_config.resource_group }}"
      name: "{{ cloud_config.security_groups.name }}"
      rules:
          - name: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.name }}"
            protocol: "{{ oud_config.security_groups.rules.inbound.allow_ssh_inbound.protocol }}"
            priority: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.priority }}"
            source_port_range: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.source }}"
            destination_port_range: "{{ cloud_config.security_groups.rules.inbound.allow_ssh_inbound.port }}"
          - name: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.name }}"
            protocol: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.protocol }}"
            priority: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.priority }}"
            source_port_range: "{{ cloud_config.security_groups.rules.inbound.allow_icmp_inbound.source }}"    
